title: "Sandman"
subtitle: "Sandman"
public_url: "https://sandman126.github.io"
keywords: "Sandman"
owner:
  name: "Sandman"
  mail: "999999(at)qq.com"
  weibo: "https://weibo.com/99999"
disqus:
  short_name: "Sandman"
paginate: 12
exclude: ["start-jekyll.sh", "start-jekyll.bat", "bower.json"]
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
host: 0.0.0.0
port: 4000
